### ISSUE TITLE
Edgar Axel Sandoval Hernández

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-1-mapa-mental-EdgarExa#3]
![MAPA CONCEPTUAL FUNDAMENTOS_012446](https://user-images.githubusercontent.com/112437707/189051515-c2ac9b7d-92b3-4f1c-951c-32d36532fed1.png)

Mapa mental - corrección

**Comment by josealfredo79** [comment]
Cual es la calificacion...debe volverse a evaluar...

**Comment by MarleneRamirez0731** [comment]
18% según la rúbrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
